// Supabase database types
// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      tasks: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          time_sensitivity: 'today' | 'this_week' | 'anytime'
          estimated_duration: number | null
          is_completed: boolean
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          time_sensitivity: 'today' | 'this_week' | 'anytime'
          estimated_duration?: number | null
          is_completed?: boolean
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          time_sensitivity?: 'today' | 'this_week' | 'anytime'
          estimated_duration?: number | null
          is_completed?: boolean
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      daily_summaries: {
        Row: {
          id: string
          user_id: string
          date: string
          completed_tasks_count: number
          created_tasks_count: number
          total_work_duration: number
          completion_rate: number
          reflection_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          completed_tasks_count?: number
          created_tasks_count?: number
          total_work_duration?: number
          completion_rate?: number
          reflection_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          completed_tasks_count?: number
          created_tasks_count?: number
          total_work_duration?: number
          completion_rate?: number
          reflection_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      pomodoro_sessions: {
        Row: {
          id: string
          user_id: string
          task_id: string | null
          session_type: 'work' | 'rest'
          start_time: string
          end_time: string | null
          duration: number
          completed: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          task_id?: string | null
          session_type: 'work' | 'rest'
          start_time?: string
          end_time?: string | null
          duration?: number
          completed?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          task_id?: string | null
          session_type?: 'work' | 'rest'
          start_time?: string
          end_time?: string | null
          duration?: number
          completed?: boolean
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
